//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;metacharset=&apos;UTF-8&apos;&gt;
        ///
        ///    &lt;metaname=&apos;viewport&apos;
        ///    content=&apos;width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0&apos;&gt;
        ///    &lt;meta http-equiv=&apos;X-UA-Compatible&apos;content=&apos;ie=edge&apos;&gt;
        ///
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///   &lt;div
        ///    style=&apos;margin: 0 auto;max-width:350px; border-radius:12px; border:2px dashed black;padding:20px; justify-content:center; align-items:center;&apos;&gt;
        ///    &lt;h2 style=&apos;color: black; margin: 0 8% 15px!important;&apos;&gt;Don&apos;t forget  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NOTIFICATION_EMAIL_HTML {
            get {
                return ResourceManager.GetString("NOTIFICATION_EMAIL_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;metacharset=&apos;UTF-8&apos;&gt;
        ///
        ///    &lt;metaname=&apos;viewport&apos;
        ///    content=&apos;width=device-width,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0&apos;&gt;
        ///    &lt;meta http-equiv=&apos;X-UA-Compatible&apos;content=&apos;ie=edge&apos;&gt;
        ///
        ///    &lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///   &lt;div
        ///    style=&apos;margin: 0 auto;max-width:350px; border-radius:12px; border:2px dashed black;padding:20px; justify-content:center; align-items:center;&apos;&gt;
        ///    &lt;h2 style=&apos;color: black; margin: 0 8% 15px!important;&apos;&gt;Please sign t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VERIFY_EMAIL_HTML {
            get {
                return ResourceManager.GetString("VERIFY_EMAIL_HTML", resourceCulture);
            }
        }
    }
}
